
[project_id]
id = "uimmjzuqdqxfqoikcexf"

[functions]
[functions.deploy]
[functions.permissions.analyze-historical-text]
include = ["auth.users.email"]
[functions.permissions.get-youtube-transcription]
include = ["*"]

[[functions.paths]]
src = "functions/*"
dest = ".functions/"
